[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts", "@openzeppelin/contracts-lib=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts"]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[invariant]
runs=128
depth=128
fail_on_revert = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
